# netlify.toml - Configuration for Netlify build and functions

[build]
  functions = "netlify-functions"   # Directory containing your serverless functions
  publish = "."  # Publish the root directory (static files if any)

[build.environment]
  FLASK_ENV = "production"  # Set the environment to production for Flask

[[redirects]]
  from = "/webhook"  # Redirect path for the webhook to the serverless function
  to = "/.netlify/functions/whatsapp_chat_bot"  # Path to the serverless function
  status = 200  # Success status code
